### ISSUE TITLE
Invalid upstream response (403) H1: OSI model en TCP/IP stack

### ISSUE THREAD

**Issue by gijsebaert** [Sleinbrein/Cybersecurity-Virtualisation#1]
![afbeelding](https://user-images.githubusercontent.com/71766951/171989558-307392eb-ccf5-4e98-8889-925edb21d9c4.png)

**Comment by gijsebaert** [comment]
Deze link gebruiken? https://cdn.educba.com/academy/wp-content/uploads/2019/07/OSI-Model-vs-TCPIP-Model.png

**Comment by Sleinbrein** [comment]
Fixed.
